import { TextFile, javascript } from "projen";

/**
 * File representing the local NPM config in .npmrc
 */
export class NpmConfigOverride extends TextFile {
    constructor(project: javascript.NodeProject) {
        const npmrcFile = project.tryFindObjectFile(".npmrc");
        // @ts-expect-error - Violate access
        const npmrcObj = npmrcFile?.obj as Record<string, string>;
        project.tryRemoveFile(".npmrc");

        super(project, ".npmrc", {
            lines: [
                '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
                "",
                ...(npmrcObj
                    ? Object.entries(npmrcObj).map(
                          ([key, value]) => `${key}=${value}`,
                      )
                    : []),
            ],
        });
    }

    /**
     * configure a scoped registry
     *
     * @param url the URL of the registry to use
     * @param scope the scope the registry is used for; leave empty for the default registry
     */
    public addRegistry(url: string, scope?: string): void {
        this.addConfig(scope ? `${scope}:registry` : "registry", url);
    }

    /**
     * configure a generic property
     *
     * @param name the name of the property
     * @param value the value of the property
     */
    public addConfig(name: string, value: string): void {
        this.addLine(`${name}=${value}`);
    }
}
